/**
 * Fix German umlauts in all source files.
 * Replaces ae→ä, oe→ö, ue→ü in German words within string literals.
 * Also fixes common ss→ß patterns.
 */
import { readFileSync, writeFileSync } from "fs";
import { execSync } from "child_process";

// Get all relevant files
const files = execSync(
  'find src -name "*.tsx" -o -name "*.ts" | grep -v node_modules | grep -v ".d.ts"',
  { cwd: "/Users/Luki/medmaster", encoding: "utf-8" }
)
  .trim()
  .split("\n")
  .filter(Boolean);

// Comprehensive German word replacement map
// Format: [pattern, replacement]
const replacements = [
  // === Common UI words ===
  ["Zurueck", "Zurück"],
  ["zurueck", "zurück"],
  ["Uebung", "Übung"],
  ["uebung", "übung"],
  ["Ueberblick", "Überblick"],
  ["ueberblick", "überblick"],
  ["Uebersicht", "Übersicht"],
  ["uebersicht", "übersicht"],
  ["Ueberpr", "Überpr"],
  ["ueberpr", "überpr"],
  ["Ueberal", "Überal"],
  ["Uebergang", "Übergang"],
  ["uebergang", "übergang"],
  ["ueber ", "über "],
  ["Ueber", "Über"],
  ["Faehig", "Fähig"],
  ["faehig", "fähig"],
  ["Verstaend", "Verständ"],
  ["verstaend", "verständ"],
  ["Naechst", "Nächst"],
  ["naechst", "nächst"],
  ["Waehle", "Wähle"],
  ["waehle", "wähle"],
  ["Waehrend", "Während"],
  ["waehrend", "während"],
  ["Aender", "Änder"],
  ["aender", "änder"],
  ["Haeufig", "Häufig"],
  ["haeufig", "häufig"],
  ["Groess", "Größ"],
  ["groess", "größ"],
  ["Grosse", "Große"],
  ["grosse", "große"],
  ["Grossen", "Großen"],
  ["grossen", "großen"],
  ["Grosser", "Großer"],
  ["grosser", "großer"],
  ["Pruef", "Prüf"],
  ["pruef", "prüf"],
  ["Staerk", "Stärk"],
  ["staerk", "stärk"],
  ["Schwaech", "Schwäch"],
  ["schwaech", "schwäch"],
  ["verfuegbar", "verfügbar"],
  ["Verfuegbar", "Verfügbar"],
  ["gueltig", "gültig"],
  ["Gueltig", "Gültig"],
  ["ungueltig", "ungültig"],
  ["Ungueltig", "Ungültig"],
  ["Woerter", "Wörter"],
  ["woerter", "wörter"],
  ["Loesung", "Lösung"],
  ["loesung", "lösung"],
  ["Loeslich", "Löslich"],
  ["loeslich", "löslich"],
  ["Loest", "Löst"],
  ["loest", "löst"],
  ["geloest", "gelöst"],
  ["aufgeloest", "aufgelöst"],
  ["Aufloesbar", "Auflösbar"],
  ["Stoech", "Stöch"],
  ["stoech", "stöch"],

  // === Medical/Science terms ===
  ["Saeure", "Säure"],
  ["saeure", "säure"],
  ["Saeuren", "Säuren"],
  ["saeuren", "säuren"],
  ["Ernaehr", "Ernähr"],
  ["ernaehr", "ernähr"],
  ["Waerme", "Wärme"],
  ["waerme", "wärme"],
  ["Koerper", "Körper"],
  ["koerper", "körper"],
  ["Hoehle", "Höhle"],
  ["hoehle", "höhle"],
  ["Hoehe", "Höhe"],
  ["hoehe", "höhe"],
  ["Hoeher", "Höher"],
  ["hoeher", "höher"],
  ["hoechst", "höchst"],
  ["Hoechst", "Höchst"],
  ["Roehr", "Röhr"],
  ["roehr", "röhr"],
  ["Stoer", "Stör"],
  ["stoer", "stör"],
  ["Zerstoer", "Zerstör"],
  ["zerstoer", "zerstör"],
  ["Gehoer", "Gehör"],
  ["gehoer", "gehör"],
  ["Behoerd", "Behörd"],
  ["Erhoeh", "Erhöh"],
  ["erhoeh", "erhöh"],
  ["Foerd", "Förd"],
  ["foerd", "förd"],
  ["befoerd", "beförd"],
  ["Koenig", "König"],
  ["koenig", "könig"],
  ["Koennen", "Können"],
  ["koennen", "können"],
  ["Moeg", "Mög"],
  ["moeg", "mög"],
  ["Noetig", "Nötig"],
  ["noetig", "nötig"],
  ["Oeffn", "Öffn"],
  ["oeffn", "öffn"],
  ["Oestrogen", "Östrogen"],
  ["oestrogen", "östrogen"],
  ["Hoer", "Hör"],
  ["hoer", "hör"],

  // ue → ü patterns
  ["Duenn", "Dünn"],
  ["duenn", "dünn"],
  ["Druese", "Drüse"],
  ["druese", "drüse"],
  ["Fluess", "Flüss"],
  ["fluess", "flüss"],
  ["Wortfluessig", "Wortflüssig"],
  ["Kuenstl", "Künstl"],
  ["kuenstl", "künstl"],
  ["Schuett", "Schütt"],
  ["schuett", "schütt"],
  ["Muend", "Münd"],
  ["muend", "münd"],
  ["Rueck", "Rück"],
  ["rueck", "rück"],
  ["Stueck", "Stück"],
  ["stueck", "stück"],
  ["Stuetz", "Stütz"],
  ["stuetz", "stütz"],
  ["Drueck", "Drück"],
  ["drueck", "drück"],
  ["Ausdrueck", "Ausdrück"],
  ["Kueh", "Küh"],
  ["kueh", "küh"],
  ["Kuerz", "Kürz"],
  ["kuerz", "kürz"],
  ["Abkuerz", "Abkürz"],
  ["Kuegel", "Kügel"],
  ["Fuehr", "Führ"],
  ["fuehr", "führ"],
  ["Ausfuehr", "Ausführ"],
  ["ausfuehr", "ausführ"],
  ["Durchfuehr", "Durchführ"],
  ["durchfuehr", "durchführ"],
  ["Einfuehr", "Einführ"],
  ["einfuehr", "einführ"],
  ["Nuetz", "Nütz"],
  ["nuetz", "nütz"],
  ["Schuetz", "Schütz"],
  ["schuetz", "schütz"],
  ["Wuensch", "Wünsch"],
  ["wuensch", "wünsch"],
  ["Spuer", "Spür"],
  ["spuer", "spür"],
  ["Tuer", "Tür"],
  ["tuer", "tür"],
  ["natuerl", "natürl"],
  ["Natuerl", "Natürl"],
  ["Wuerfel", "Würfel"],
  ["wuerfel", "würfel"],
  ["Buendel", "Bündel"],
  ["buendel", "bündel"],

  // === ß patterns (specific words only) ===
  ["Schliessen", "Schließen"],
  ["schliessen", "schließen"],
  ["Ausloes", "Auslös"],
  ["ausloes", "auslös"],
  ["Anschluss", "Anschluss"], // stays as-is (short vowel)
  ["Schluss", "Schluss"], // stays as-is
  ["Weiss", "Weiß"],
  ["weiss", "weiß"],
  ["Heiss", "Heiß"],
  ["heiss", "heiß"],
  ["Fliess", "Fließ"],
  ["fliess", "fließ"],
  ["Aussen", "Außen"],
  ["aussen", "außen"],
  ["Ausserhalb", "Außerhalb"],
  ["ausserhalb", "außerhalb"],
  ["Aeusser", "Äußer"],
  ["aeusser", "äußer"],
  ["Schuesse", "Schüsse"],
  ["Strasse", "Straße"],
  ["strasse", "straße"],
  ["Reissverschluss", "Reißverschluss"],
  ["Massnahme", "Maßnahme"],
  ["massnahme", "maßnahme"],
  ["Massgeblich", "Maßgeblich"],
  ["massgeblich", "maßgeblich"],
  ["Regelmässig", "Regelmäßig"],
  ["regelmaessig", "regelmäßig"],
  ["Maessig", "Mäßig"],
  ["maessig", "mäßig"],
  ["Gemäss", "Gemäß"],

  // More medical terms
  ["Praemisse", "Prämisse"],
  ["praemisse", "prämisse"],
  ["Praeg", "Präg"],
  ["praeg", "präg"],
  ["Praezis", "Präzis"],
  ["praezis", "präzis"],
  ["Praevent", "Prävent"],
  ["praevent", "prävent"],
  ["Praeparat", "Präparat"],
  ["praeparat", "präparat"],
  ["Praesentier", "Präsentier"],
  ["praesentier", "präsentier"],
  ["Praesent", "Präsent"],
  ["praesent", "präsent"],
  ["Praefix", "Präfix"],
  ["praefix", "präfix"],
  ["Praedikat", "Prädikat"],
  ["praedikat", "prädikat"],
  ["Praedisp", "Prädisp"],
  ["praedisp", "prädisp"],
  ["Praenatal", "Pränatal"],
  ["praenatal", "pränatal"],
  ["Praeferenz", "Präferenz"],
  ["Praesynapt", "Präsynapt"],
  ["praesynapt", "präsynapt"],
  ["Praeparier", "Präparier"],
  ["praepar", "präpar"],
  ["Primaer", "Primär"],
  ["primaer", "primär"],
  ["Sekundaer", "Sekundär"],
  ["sekundaer", "sekundär"],
  ["Tertiaer", "Tertiär"],
  ["tertiaer", "tertiär"],
  ["Quartaer", "Quartär"],
  ["quartaer", "quartär"],
  ["Kaelte", "Kälte"],
  ["kaelte", "kälte"],
  ["Sphaere", "Sphäre"],
  ["sphaere", "sphäre"],
  ["Vollstaend", "Vollständ"],
  ["vollstaend", "vollständ"],
  ["Unstaend", "Umständ"],
  ["unstaend", "umständ"],
  ["Selbstaend", "Selbständ"],
  ["selbstaend", "selbständ"],
  ["Staend", "Ständ"],
  ["staend", "ständ"],
  ["Schaed", "Schäd"],
  ["schaed", "schäd"],
  ["Schaetz", "Schätz"],
  ["schaetz", "schätz"],
  ["Spaet", "Spät"],
  ["spaet", "spät"],
  ["Naehr", "Nähr"],
  ["naehr", "nähr"],
  ["Gefaess", "Gefäß"],
  ["gefaess", "gefäß"],
  ["Gefaehr", "Gefähr"],
  ["gefaehr", "gefähr"],
  ["Laeng", "Läng"],
  ["laeng", "läng"],
  ["Faell", "Fäll"],
  ["faell", "fäll"],
  ["Faech", "Fäch"],
  ["faech", "fäch"],
  ["Faehr", "Fähr"],
  ["faehr", "fähr"],
  ["Gaer", "Gär"],
  ["gaer", "gär"],
  ["Jaehr", "Jähr"],
  ["jaehr", "jähr"],
  ["Maenn", "Männ"],
  ["maenn", "männ"],
  ["Naeh", "Näh"],
  ["naeh", "näh"],
  ["Taet", "Tät"],
  ["taet", "tät"],
  ["Taeusch", "Täusch"],
  ["taeusch", "täusch"],
  ["Waess", "Wäss"],
  ["waess", "wäss"],
  ["Zaeh", "Zäh"],
  ["zaeh", "zäh"],
  ["Zaehlung", "Zählung"],
  ["Saett", "Sätt"],
  ["saett", "sätt"],
  ["Blaett", "Blätt"],
  ["blaett", "blätt"],
  ["faelsch", "fälsch"],
  ["Faelsch", "Fälsch"],
  ["Kaelt", "Kält"],
  ["kaelt", "kält"],
  ["Staerke", "Stärke"],
  ["staerke", "stärke"],
  ["Schaerfe", "Schärfe"],
  ["schaerfe", "schärfe"],
  ["Haem", "Häm"],
  ["haem", "häm"],
  ["Haeuf", "Häuf"],
  ["haeuf", "häuf"],
  ["Haelt", "Hält"],
  ["haelt", "hält"],
  ["enthaelt", "enthält"],
  ["Erhaelt", "Erhält"],
  ["erhaelt", "erhält"],
  ["Behaelt", "Behält"],
  ["behaelt", "behält"],
  ["Haeng", "Häng"],
  ["haeng", "häng"],
  ["abhaeng", "abhäng"],
  ["Abhaeng", "Abhäng"],
  ["zusammenhaeng", "zusammenhäng"],
  ["Zusammenhaeng", "Zusammenhäng"],
  ["Raeum", "Räum"],
  ["raeum", "räum"],
  ["Waerm", "Wärm"],
  ["waerm", "wärm"],
  ["Schaedel", "Schädel"],
  ["Traeg", "Träg"],
  ["traeg", "träg"],
  ["Kaef", "Käf"],

  // ö patterns
  ["Hoehle", "Höhle"],
  ["hoehle", "höhle"],
  ["Voellig", "Völlig"],
  ["voellig", "völlig"],
  ["Voelk", "Völk"],
  ["voelk", "völk"],
  ["Woech", "Wöch"],
  ["woech", "wöch"],
  ["Toet", "Töt"],
  ["toet", "töt"],
  ["abtoet", "abtöt"],
  ["Boes", "Bös"],
  ["boes", "bös"],
  ["Groesst", "Größt"],
  ["groesst", "größt"],
  ["Moeglic", "Möglic"],
  ["moeglic", "möglic"],
  ["Knoech", "Knöch"],
  ["knoech", "knöch"],
  ["Loech", "Löch"],
  ["loech", "löch"],
  ["Stoech", "Stöch"],
  ["stoech", "stöch"],
  ["Hoechst", "Höchst"],
  ["hoechst", "höchst"],
  ["gehoer", "gehör"],
  ["Gehoer", "Gehör"],
  ["Erhoeh", "Erhöh"],
  ["erhoeh", "erhöh"],

  // Remaining ü patterns
  ["Einfuell", "Einfüll"],
  ["Ausfuell", "Ausfüll"],
  ["Gefuehl", "Gefühl"],
  ["gefuehl", "gefühl"],
  ["Einfuehl", "Einfühl"],
  ["einfuehl", "einfühl"],
  ["Fuell", "Füll"],
  ["fuell", "füll"],
  ["Huell", "Hüll"],
  ["huell", "hüll"],
  ["Gueltig", "Gültig"],
  ["Muell", "Müll"],
  ["muell", "müll"],
  ["Kuend", "Künd"],
  ["kuend", "künd"],
  ["Gruend", "Gründ"],
  ["gruend", "gründ"],
  ["Begruend", "Begründ"],
  ["begruend", "begründ"],
  ["Wuerde", "Würde"],
  ["wuerde", "würde"],
  ["Buerger", "Bürger"],
  ["buerger", "bürger"],
  ["Buerg", "Bürg"],
  ["Lueck", "Lück"],
  ["lueck", "lück"],
  ["Glueck", "Glück"],
  ["glueck", "glück"],

  // Very specific science terms
  ["Transkript", "Transkript"], // stays
  ["Rezept", "Rezept"], // stays
  ["Nukle", "Nukle"], // stays (not an umlaut)
  ["Antikoerper", "Antikörper"],
  ["antikoerper", "antikörper"],
  ["Aminosaeure", "Aminosäure"],
  ["aminosaeure", "aminosäure"],
  ["Fettsaeure", "Fettsäure"],
  ["fettsaeure", "fettsäure"],
  ["Gallensaeure", "Gallensäure"],
  ["gallensaeure", "gallensäure"],
  ["Nucleinsaeure", "Nucleinsäure"],
  ["Nukleinsaeure", "Nukleinsäure"],
  ["Schilddruese", "Schilddrüse"],
  ["schilddruese", "schilddrüse"],
  ["Nebenniere", "Nebenniere"], // correct already
  ["Auspraeg", "Auspräg"],
  ["auspraeg", "auspräg"],
  ["Basenpaar", "Basenpaar"], // correct already
  ["Doppelmembran", "Doppelmembran"], // correct
  ["Chromosomenaberr", "Chromosomenaberr"], // correct
  ["Zellmembranab", "Zellmembranab"],
  ["Homoeoest", "Homöost"],
  ["homoeoest", "homöost"],
  ["Homoeo", "Homöo"],
  ["homoeo", "homöo"],

  // Remaining patterns that appear in content
  ["Ploetzlich", "Plötzlich"],
  ["ploetzlich", "plötzlich"],
  ["Voellig", "Völlig"],
  ["voellig", "völlig"],
  ["Zunaechst", "Zunächst"],
  ["zunaechst", "zunächst"],
  ["naemlich", "nämlich"],
  ["Naemlich", "Nämlich"],
  ["ungefaehr", "ungefähr"],
  ["Ungefaehr", "Ungefähr"],
  ["taeglich", "täglich"],
  ["Taeglich", "Täglich"],
  ["zusaetzlich", "zusätzlich"],
  ["Zusaetzlich", "Zusätzlich"],
  ["waessrig", "wässrig"],
  ["Waessrig", "Wässrig"],
  ["Stuetzgewebe", "Stützgewebe"],
  ["Schutzhuell", "Schutzhüll"],
  ["Hueft", "Hüft"],
  ["hueft", "hüft"],
  ["Buendig", "Bündig"],

  // Catch remaining common suffixes
  ["Aktivitaet", "Aktivität"],
  ["Qualitaet", "Qualität"],
  ["Quantitaet", "Quantität"],
  ["Kontinuitaet", "Kontinuität"],
  ["Spezifitaet", "Spezifität"],
  ["Sensitivitaet", "Sensitivität"],
  ["Kapazitaet", "Kapazität"],
  ["Komplexitaet", "Komplexität"],
  ["Elektrizitaet", "Elektrizität"],
  ["Viskositaet", "Viskosität"],
  ["Polaritaet", "Polarität"],
  ["Integritaet", "Integrität"],
  ["Identitaet", "Identität"],
  ["Gravitaet", "Gravität"],
  ["Relativitaet", "Relativität"],
  ["Universitaet", "Universität"],
  ["Immunitaet", "Immunität"],
  ["Humanitaet", "Humanität"],
  ["Normalitaet", "Normalität"],
  ["Mortalitaet", "Mortalität"],
  ["itaet", "ität"],
  ["Stabilitaet", "Stabilität"],

  // Common ue in middle of words
  ["Ausfuehr", "Ausführ"],
  ["Durchfuehr", "Durchführ"],
  ["Einfuehr", "Einführ"],
  ["zufuehr", "zuführ"],
  ["Zufuehr", "Zuführ"],
  ["Ausfuell", "Ausfüll"],
  ["Erfuell", "Erfüll"],
  ["erfuell", "erfüll"],
  ["Verfueg", "Verfüg"],
  ["verfueg", "verfüg"],

  // Words with äu
  ["Gebaeu", "Gebäu"],
  ["gebaeu", "gebäu"],
  ["Saeu", "Säu"],
  ["saeu", "säu"],
  ["Haeut", "Häut"],
  ["haeut", "häut"],
  ["Laeu", "Läu"],
  ["laeu", "läu"],
  ["Traeume", "Träume"],
  ["traeume", "träume"],

  // Catch-all for common endings
  ["aere ", "äre "],
  ["oese ", "öse "],
  ["oesen", "ösen"],
  ["aehn", "ähn"],
  ["Aehn", "Ähn"],

  // Common words that weren't covered
  ["Einfuell", "Einfüll"],
  ["ausgefuehrt", "ausgeführt"],
  ["durchgefuehrt", "durchgeführt"],
  ["Frueher", "Früher"],
  ["frueher", "früher"],
  ["Frueh", "Früh"],
  ["frueh", "früh"],
  ["Schueler", "Schüler"],
  ["schueler", "schüler"],
  ["Muetter", "Mütter"],
  ["muetter", "mütter"],
  ["Brueder", "Brüder"],
  ["brueder", "brüder"],
  ["Bruecke", "Brücke"],
  ["bruecke", "brücke"],
  ["Stuehle", "Stühle"],
  ["Buech", "Büch"],
  ["buech", "büch"],
  ["Wuest", "Wüst"],
  ["wuest", "wüst"],
];

let totalChanges = 0;
const changedFiles = [];

for (const relPath of files) {
  const fullPath = `/Users/Luki/medmaster/${relPath}`;
  let content;
  try {
    content = readFileSync(fullPath, "utf-8");
  } catch {
    continue;
  }

  let newContent = content;
  let fileChanges = 0;

  for (const [pattern, replacement] of replacements) {
    if (pattern === replacement) continue; // skip identity replacements

    // Replace in string literals and JSX text
    const regex = new RegExp(pattern, "g");
    const before = newContent;
    newContent = newContent.replace(regex, (match, offset) => {
      // Don't replace in import paths
      const lineStart = newContent.lastIndexOf("\n", offset) + 1;
      const line = newContent.substring(lineStart, newContent.indexOf("\n", offset));
      if (line.trimStart().startsWith("import ") && line.includes("from")) return match;

      // Don't replace in type definitions or variable names that are purely code
      // Actually, we want to replace everywhere except import paths and identifiers
      // The key insight: all these German words appear in string content, not as JS identifiers

      return replacement;
    });

    if (newContent !== before) {
      const count = (before.match(regex) || []).length - (newContent === before ? 0 : 0);
      fileChanges++;
    }
  }

  if (newContent !== content) {
    writeFileSync(fullPath, newContent, "utf-8");
    const changes = content
      .split("\n")
      .filter((line, i) => line !== newContent.split("\n")[i]).length;
    changedFiles.push({ file: relPath, linesChanged: changes });
    totalChanges += changes;
  }
}

console.log(`\nFixed ${changedFiles.length} files, ~${totalChanges} lines changed:`);
changedFiles.forEach(({ file, linesChanged }) => {
  console.log(`  ${file} (${linesChanged} lines)`);
});
