/**
 * Generates 1000 Implikationen tasks (400 easy, 400 medium, 200 hard) as static TS pool.
 * Run: npx tsx scripts/generate-ie-1000.mts
 */
import { writeFileSync } from "fs";
import { resolve } from "path";
import {
  generateImplicationTask,
  type ImplikationTask,
} from "../src/data/kffImplikationen";

const TARGETS: { level: 1 | 2 | 3; count: number }[] = [
  { level: 1, count: 400 },
  { level: 2, count: 400 },
  { level: 3, count: 200 },
];

function main() {
  const tasks: ImplikationTask[] = [];
  let discarded = 0;

  // Deduplicate by premise pair
  const seenPremises = new Set<string>();

  for (const { level, count } of TARGETS) {
    let generated = 0;
    let attempts = 0;
    const maxAttempts = count * 20; // IE generator uses randomness, needs more headroom

    while (generated < count && attempts < maxAttempts) {
      attempts++;
      const task = generateImplicationTask(level);

      if (!task) {
        discarded++;
        continue;
      }

      // Deduplicate by premise content
      const premiseKey = `${task.premise1}|${task.premise2}`;
      if (seenPremises.has(premiseKey)) {
        discarded++;
        continue;
      }

      seenPremises.add(premiseKey);
      // Renumber ID
      task.id = `ie-${String(tasks.length + 1).padStart(4, "0")}`;
      tasks.push(task);
      generated++;
    }

    if (generated < count) {
      console.warn(`WARNING: Only ${generated}/${count} for difficulty ${level} (${attempts} attempts)`);
    }
  }

  // --- Statistics ---
  const byDiff: Record<number, number> = { 1: 0, 2: 0, 3: 0 };
  const byCorrect: Record<number, number> = { 0: 0, 1: 0, 2: 0, 3: 0, 4: 0 };

  for (const t of tasks) {
    byDiff[t.difficulty]++;
    byCorrect[t.correctAnswer]++;
  }

  const eCount = byCorrect[4]; // index 4 = option E
  console.log(`\n=== Implikationen 1000 Generation ===`);
  console.log(`Total: ${tasks.length}`);
  console.log(`Discarded: ${discarded}`);
  console.log(`\nDifficulty: 1=${byDiff[1]} 2=${byDiff[2]} 3=${byDiff[3]}`);
  console.log(`Correct: A=${byCorrect[0]} B=${byCorrect[1]} C=${byCorrect[2]} D=${byCorrect[3]} E=${byCorrect[4]} (${((eCount / tasks.length) * 100).toFixed(1)}%)`);

  // --- Write TS file ---
  const lines: string[] = [
    `// Auto-generated by generate-ie-1000.mts — ${tasks.length} validated Implikationen tasks.`,
    `// Distribution: easy ${byDiff[1]}, medium ${byDiff[2]}, hard ${byDiff[3]}`,
    `// E-correct: ${eCount} (${((eCount / tasks.length) * 100).toFixed(1)}%)`,
    ``,
    `import type { ImplikationTask } from "./kffImplikationen";`,
    ``,
    `export const IMPLIKATIONEN_POOL: ImplikationTask[] = ${JSON.stringify(tasks, null, 2)};`,
  ];

  const outPath = resolve(process.cwd(), "src/data/kffImplikationen1000.ts");
  writeFileSync(outPath, lines.join("\n") + "\n", "utf-8");
  console.log(`\nWritten to: ${outPath}`);
}

main();
