/**
 * Generates 1000 Figuren-zusammensetzen tasks (200 easy, 600 medium, 200 hard) as static TS pool.
 * Enforces balanced Shape-Verteilung across all 15 SOLUTION_SHAPES to avoid Quadrat-Overrepresentation.
 * Run: npx tsx scripts/generate-fz-1000.mts
 */
import { writeFileSync } from "fs";
import { resolve } from "path";
import {
  generateFigurenTrainingTask,
  validateFigurenTask,
  SOLUTION_SHAPES,
  type FigureAssembleTask,
} from "../src/data/kffFigurenZusammensetzenMedAT";

type FZDifficulty = "easy" | "medium" | "hard";

const TARGETS: { level: FZDifficulty; count: number }[] = [
  { level: "easy", count: 200 },
  { level: "medium", count: 600 },
  { level: "hard", count: 200 },
];

function main() {
  const tasks: FigureAssembleTask[] = [];
  let discarded = 0;
  const numShapes = SOLUTION_SHAPES.length;

  for (const { level, count } of TARGETS) {
    // Enforce balanced distribution: ~count/numShapes per shape (round-robin with explicit targets)
    const perShapeTarget = Math.floor(count / numShapes);
    const remainder = count - perShapeTarget * numShapes;
    const perShapeTargets = Array(numShapes).fill(perShapeTarget).map((n, i) => n + (i < remainder ? 1 : 0));
    const perShapeDone = Array(numShapes).fill(0);

    let generated = 0;
    let attempts = 0;
    const maxAttempts = count * 400;

    while (generated < count && attempts < maxAttempts) {
      attempts++;

      // Pick shape that is furthest from its target (round-robin fair)
      let shapeIdx = 0;
      let worstDeficit = -Infinity;
      for (let i = 0; i < numShapes; i++) {
        const deficit = perShapeTargets[i] - perShapeDone[i];
        if (deficit > worstDeficit) {
          worstDeficit = deficit;
          shapeIdx = i;
        }
      }
      // All shapes at target → done
      if (worstDeficit <= 0) break;

      const seed = attempts * 7919 + tasks.length * 13 + shapeIdx * 99991;

      try {
        const task = generateFigurenTrainingTask(level, seed, shapeIdx);
        if (!task || task.pieces.length < 2) {
          discarded++;
          continue;
        }

        if (!validateFigurenTask(task, true)) {
          discarded++;
          continue;
        }

        tasks.push(task);
        perShapeDone[shapeIdx]++;
        generated++;

        if (generated % 100 === 0) {
          console.log(`  ${level}: ${generated}/${count} (${attempts} attempts, ${discarded} discarded)`);
        }
      } catch {
        discarded++;
      }
    }

    console.log(`${level}: ${generated}/${count} done (${attempts} attempts, shape-distribution: ${perShapeDone.join(",")})`);
  }

  console.log(`\nTotal: ${tasks.length} tasks, ${discarded} discarded`);

  // Per-shape stats
  const shapeCounts: Record<string, number> = {};
  const correctCounts = { 0: 0, 1: 0, 2: 0, 3: 0, 4: 0 };
  for (const t of tasks) {
    const shape = (t as any).solutionShapeId || (t as any).solutionShape || "unknown";
    shapeCounts[shape] = (shapeCounts[shape] || 0) + 1;
    if (typeof t.correctIndex === "number" && t.correctIndex >= 0 && t.correctIndex <= 4) {
      correctCounts[t.correctIndex as 0 | 1 | 2 | 3 | 4]++;
    }
  }
  console.log("\nShape distribution:");
  for (const [shape, n] of Object.entries(shapeCounts).sort((a, b) => b[1] - a[1])) {
    console.log(`  ${shape.padEnd(22)} ${String(n).padStart(4)}  (${((n / tasks.length) * 100).toFixed(1)}%)`);
  }
  const ePct = ((correctCounts[4] / tasks.length) * 100).toFixed(1);
  console.log(`\nCorrect option distribution: A=${correctCounts[0]} B=${correctCounts[1]} C=${correctCounts[2]} D=${correctCounts[3]} E=${correctCounts[4]} (${ePct}%)`);

  // Chunk into 4 files to stay under file-size limits
  const CHUNKS = 4;
  const chunkSize = Math.ceil(tasks.length / CHUNKS);
  for (let c = 1; c <= CHUNKS; c++) {
    const chunk = tasks.slice((c - 1) * chunkSize, c * chunkSize);
    const chunkPath = resolve(import.meta.dirname, `../src/data/kffFiguren1000_chunk${c}.ts`);
    const header = `// Auto-generated by generate-fz-1000.mts — Chunk ${c}/${CHUNKS} (${chunk.length} tasks).\n`;
    writeFileSync(
      chunkPath,
      header + `import type { FigureAssembleTask } from "./kffFigurenZusammensetzenMedAT";\n\n` +
        `export const FIGUREN_POOL_CHUNK_${c}: FigureAssembleTask[] = ${JSON.stringify(chunk, null, 0)};\n`,
      "utf-8"
    );
    console.log(`Written chunk ${c}: ${chunk.length} tasks`);
  }
}

main();
