/**
 * Generates 1000 Zahlenfolgen tasks (400 easy, 400 medium, 200 hard) as static TS pool.
 * Run: npx tsx scripts/generate-zf-1000.mts
 */
import { writeFileSync } from "fs";
import { resolve } from "path";
import {
  generateSequenceTask,
  validateSequenceTask,
  type SequenceTask,
  type DifficultyLevel,
} from "../src/data/kffZahlenfolgenMedAT";

const TARGETS: { level: DifficultyLevel; count: number }[] = [
  { level: "easy", count: 400 },
  { level: "medium", count: 400 },
  { level: "hard", count: 200 },
];

function main() {
  const tasks: SequenceTask[] = [];
  let discarded = 0;
  let globalIdx = 0;

  // Use unique set to avoid duplicate sequences
  const seenSequences = new Set<string>();

  for (const { level, count } of TARGETS) {
    let generated = 0;
    let attempts = 0;
    const maxAttempts = count * 30;

    while (generated < count && attempts < maxAttempts) {
      const seed = 300_000 + globalIdx * 6271 + attempts * 37 + (level === "easy" ? 500_000 : 0);
      const task = generateSequenceTask(level, seed);
      attempts++;

      if (!validateSequenceTask(task)) {
        discarded++;
        continue;
      }

      // Deduplicate by visible sequence
      const seqKey = task.sequence.join(",");
      if (seenSequences.has(seqKey)) {
        discarded++;
        continue;
      }

      seenSequences.add(seqKey);
      globalIdx++;
      task.id = `zf-${String(tasks.length + 1).padStart(4, "0")}`;
      tasks.push(task);
      generated++;
    }

    if (generated < count) {
      console.warn(`WARNING: Only ${generated}/${count} for ${level} (${attempts} attempts)`);
    }
  }

  // --- Statistics ---
  const byDiff: Record<string, number> = { easy: 0, medium: 0, hard: 0 };
  const byCorrect: Record<string, number> = { A: 0, B: 0, C: 0, D: 0, E: 0 };

  for (const t of tasks) {
    byDiff[t.difficulty]++;
    byCorrect[t.correctOptionId]++;
  }

  console.log(`\n=== Zahlenfolgen 1000 Generation ===`);
  console.log(`Total: ${tasks.length}`);
  console.log(`Discarded: ${discarded}`);
  console.log(`\nDifficulty: easy=${byDiff.easy} medium=${byDiff.medium} hard=${byDiff.hard}`);
  console.log(`Correct: A=${byCorrect.A} B=${byCorrect.B} C=${byCorrect.C} D=${byCorrect.D} E=${byCorrect.E} (${((byCorrect.E / tasks.length) * 100).toFixed(1)}%)`);

  // --- Write TS file ---
  const lines: string[] = [
    `// Auto-generated by generate-zf-1000.mts — ${tasks.length} validated Zahlenfolgen tasks.`,
    `// Distribution: easy ${byDiff.easy}, medium ${byDiff.medium}, hard ${byDiff.hard}`,
    `// E-correct: ${byCorrect.E} (${((byCorrect.E / tasks.length) * 100).toFixed(1)}%)`,
    ``,
    `import type { SequenceTask } from "./kffZahlenfolgenMedAT";`,
    ``,
    `export const ZAHLENFOLGEN_POOL: SequenceTask[] = ${JSON.stringify(tasks, null, 2)};`,
  ];

  const outPath = resolve(process.cwd(), "src/data/kffZahlenfolgen1000.ts");
  writeFileSync(outPath, lines.join("\n") + "\n", "utf-8");
  console.log(`\nWritten to: ${outPath}`);
}

main();
